### ISSUE TITLE
OSX Build Error: OSError: error running 'unzip -q -d macosx macosx.zip': 9

### ISSUE THREAD

**Issue by justquick** [ActiveState/OpenKomodoIDE#5]
When following the readme's instructions to build on my mac i get an error during `build.py configure` where it is unable to unzip the prebuilt zip because the files seem to be git LFS pointers. The readme does not mention any lfs requirement or steps to download those zipfiles. How can I download those zipfiles so I can build komodo?

## Steps to reproduce

- `python2.7 build.py configure -k 10.10`

## Exception

```
target: configure
/bin/sh: svnversion: command not found
build: warning: Failed to get changenum, using 0 instead
unzipping prebuilt python in `prebuilt/python2.7/macosx'
[macosx.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of macosx.zip or
        macosx.zip.zip, and cannot find macosx.zip.ZIP, period.
Traceback (most recent call last):
  File "build.py", line 2910, in <module>
    sys.exit( main(sys.argv) )
  File "build.py", line 2906, in main
    return build(args)
  File "build.py", line 2730, in build
    newArgv = targetFunc(argv)
  File "build.py", line 1297, in target_configure
    dirname(prebuiltDir), log.debug)
  File "build.py", line 214, in _run_in_dir
    _run(cmd, logstream=None)
  File "build.py", line 196, in _run
    raise OSError("error running '%s': %r" % (cmd, status))
OSError: error running 'unzip -q -d macosx macosx.zip': 9
```

**Comment by th3coop** [comment]
This is due to me, last minute, setting up git LFS to accommodate the Komodo installers.  I'd suggest either opening a PR to remove anything but the `installers` directory from LFS or Googling how to have Git pull down LFS files, and if you're feeling up for it, opening a PR to update the README with those instructions.  But I think removing unnecessary files from LFS is probably the better idea.

**Comment by justquick** [comment]
what about using github releases? having the installers available to download instead of building it myself if possible seems like an ideal way to get up and running quickly

**Comment by AhmedEzzat12** [comment]
> what about using github releases? having the installers available to download instead of building it myself if possible seems like an ideal way to get up and running quickly

I second that!

**Comment by th3coop** [comment]
Oh that's a great idea, @justquick.  Just fyi, you don't need to build anything.  The installers in the [installers](https://github.com/ActiveState/OpenKomodoIDE/tree/master/installers) directory can be downloaded right now and run.  I'll move those to a release soon.

**Comment by th3coop** [comment]
@justquick any chance you can checkout `th3oop/remove-installers-disable-git-lfs` and see if you still get the error?  I'm having a hell of a time untangling git lfs from the repo.  What a nightmare that tool is.  

FYI, I created a release for IDE: https://github.com/ActiveState/OpenKomodoIDE/releases/tag/12.0.1
and Edit: https://github.com/komodo/KomodoEdit/releases/tag/12.0.1
