### ISSUE TITLE
Can't build/install on Ubuntu

### ISSUE THREAD

**Issue by igoryonya** [ActiveState/OpenKomodoIDE#7]
I am trying to follow the installation instructions:
I've installed prerequisites for Ubuntu (Ubuntu 20.04.5 LTS).
Then, rand the python build configure command and it gives me an error.
I've found linux-x86_64.zip in the repo dir, tried to "unzip -t linux-x86_64.zip" but it gave me an error, so I've looked inside of it: "less linux-x86_64.zip" and it has only text "Archive:  prebuilt/python2.7/linux-x86_64.zip" inside.

How can I solve it?

```
user:/tmp/1/OpenKomodoIDE/mozilla$ python2 build.py configure -k 10.10
target: configure
/bin/sh: 1: svnversion: not found
build: warning: Failed to get changenum, using 0 instead
unzipping prebuilt python in `prebuilt/python2.7/linux-x86_64'
[linux-x86_64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of linux-x86_64.zip or
        linux-x86_64.zip.zip, and cannot find linux-x86_64.zip.ZIP, period.
Traceback (most recent call last):
  File "build.py", line 2910, in <module>
    sys.exit( main(sys.argv) )
  File "build.py", line 2906, in main
    return build(args)
  File "build.py", line 2730, in build
    newArgv = targetFunc(argv)
  File "build.py", line 1297, in target_configure
    dirname(prebuiltDir), log.debug)
  File "build.py", line 214, in _run_in_dir
    _run(cmd, logstream=None)
  File "build.py", line 196, in _run
    raise OSError("error running '%s': %r" % (cmd, status))
OSError: error running 'unzip -q -d linux-x86_64 linux-x86_64.zip': 9

```

**Comment by th3coop** [comment]
Same as #5.  Try checking out th3oop/remove-installers-disable-git-lfs branch and try the command again.  Report back on #5.
